name: Hello springboot App to Docker

on:
    push:
       

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:

            - name: checkout code
              uses: actions/checkout@v4

            - name: setup JDK
              uses: actions/setup-java@v5
              with:
                    distribution: 'temurin' # See 'Supported distributions' for available options
                    java-version: '21'

            - name: Build and Test(maven)
              working-directory: Devops/app1-hello/springboot/hello-spring 
              run: mvn -B clean verify

            - name: Upload Test Reports
              uses: actions/upload-artifact@v4
              with:
                    name: test-reports

                    path: Devops/app1-hello/springboot/hello-spring/target/surefire-reports


    docker-build-push:
        runs-on: ubuntu-latest
        needs: build-test
        steps:

            - name: checkout code
              run: echo ""

            - name: setup JDK
              run: echo ""

            - name: Build JAR for Docker
              run: echo ""

            - name: Login to DockerHub
              run: echo ""

            - name: Build and push docker image
              run: echo ""
